name: leaf-db

services:
  postgres:
    image: postgres:17.5
    container_name: leaf-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: leaf
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: